import express, { application } from 'express';
import { protectRoute } from '../middleware/auth.middleware.js';
const router=express.Router();
import {login,logout,signup,update_profile,checkAuth} from '../controllers/auth.controllers.js'; 
router.post("/signup",signup);
router.post("/login",login);
router.post("/logout",logout);
router.put("/updateprofile",protectRoute,update_profile);
router.get("/check",protectRoute,checkAuth);
export default router;